### ISSUE TITLE
ValueError: Illegal chunk pattern: {<N.*>{4,}}

### ISSUE THREAD

**Issue by drussellmrichie** [nltk/nltk_book#129]
The "Your Turn" in 2.4 of chapter 7 suggests encapsulating the example into a function and using a different chunk pattern: "NOUNS: {<N.*>{4,}}". I'm using Python 2.7 with NLTK 3.0.1

I tried that (not the function part, just the different chunk pattern), as in the snippet below

    cp = nltk.RegexpParser("NOUNS: {<N.*>{4,}}")
    brown = nltk.corpus.brown
    for sent in brown.tagged_sents():
        tree = cp.parse(sent)
        for subtree in tree.subtrees():
        if subtree.label() == 'NOUNS': print(subtree)

And got this error: 

    Traceback (most recent call last):
      File "/Users/russellrichie/anaconda/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 3032, in run_code
        exec(code_obj, self.user_global_ns, self.user_ns)
      File "<ipython-input-33-243b8af6aea3>", line 1, in <module>
        cp = nltk.RegexpParser("NOUNS: {<N.*>{4,}}")
      File "/Users/russellrichie/anaconda/lib/python2.7/site-packages/nltk/chunk/regexp.py", line 1130, in __init__
        self._read_grammar(grammar, root_label, trace)
      File "/Users/russellrichie/anaconda/lib/python2.7/site-packages/nltk/chunk/regexp.py", line 1166, in _read_grammar
        rules.append(RegexpChunkRule.fromstring(line))
      File "/Users/russellrichie/anaconda/lib/python2.7/site-packages/nltk/chunk/regexp.py", line 381, in fromstring
        raise ValueError('Illegal chunk pattern: %s' % rule)
    ValueError: Illegal chunk pattern: {<N.*>{4,}}

A little bit of testing revealed that it seems not to like any {#} regex syntax.

**Comment by stevenbird** [comment]
Thanks @drussellmrichie. Yes, the task is asking for something that is not supported in the ChunkRule syntax. I'm surprised this has not been reported before. We need to modify the task or the syntax!

**Comment by ewan-klein** [comment]
Consider making ChunkRule syntax more flexible? Text is now adjusted so that task is doable.
